dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-installer-linux-x86_64.sh
  - sha256sum -c .travis.bazel-0.14.1-installer-linux-x86_64.sh.sha256
  - bash bazel-0.14.1-installer-linux-x86_64.sh --user
  - go get -u github.com/swaggo/swag/cmd/swag

script:
- mkdir -p $HOME/gopath/src/github.com/invly/
- ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/invly/invly || true
- cp .bazelrc.travis .bazelrc
- bazel test //...