package main

import (
	"log"
	"net/http"

	"github.com/invly/invly/api"

	"github.com/gorilla/mux"
	_ "github.com/invly/invly/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/http-swagger"
)

// @title invly
// @version 1.0
// @description Simple inventory management

// @contact.name Fabian Cernota
// @contact.url http://invly.de
// @contact.email fabs@invly.de

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8000
// @BasePath /
func main() {
	router := mux.NewRouter()
	api.AddV1Handler(router)
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)
	log.Fatal(http.ListenAndServe(":8000", router))
}
